version: '3'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      target: client
    ports:
      - "3000:3000"  # Assuming React server runs on port 3000

  backend:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    ports:
      - "5001:5001"  # Assuming Flask server runs on port 5001
